Imports System.Collections.Generic
Imports System.Linq
Imports System.Web


Public Class IPNHolder



    '_txnID,_txnType, _paymentStatus, _receiverEmail, _itemName, _itemNumber, _quantity, _invoice, _custom,
    '_paymentGross, _payerEmail, _pendingReason, _paymentDate, _paymentFee,_firstName, _lastName, _address, 
    '_city, _state, _zip, _country, _countryCode, _addressStatus, _payerStatus, _payerID, _paymentType, _notifyVersion,
    '_verifySign, _response, _payerPhone, _payerBusinessName, _business, _receiverID, _memo, _tax, _qtyCartItems,
    '_shippingMethod, _shipping;

    Public _txnID As String, _txnType As String, _paymentStatus As String, _receiverEmail As String, _itemName As String, _itemNumber As String, _
     _quantity As String, _invoice As String, _custom As String, _paymentGross As String, _payerEmail As String, _pendingReason As String, _
     _paymentDate As String, _paymentFee As String, _firstName As String, _lastName As String, _address As String, _city As String, _
     _state As String, _zip As String, _country As String, _countryCode As String, _addressStatus As String, _payerStatus As String, _
     _payerID As String, _paymentType As String, _notifyVersion As String, _verifySign As String, _response As String, _payerPhone As String, _
     _payerBusinessName As String, _business As String, _receiverID As String, _memo As String, _tax As String, _qtyCartItems As String, _
     _shippingMethod As String, _shipping As String, _currency As String

    Private _postUrl As String = ""
    Private _strRequest As String = ""
    Private _smtpHost As String, _fromEmail As String, _toEmail As String, _fromEmailPassword As String, _smtpPort As String


#Region "Properties"

    Private Property PostUrl() As String
        Get
            Return _postUrl
        End Get
        Set(value As String)
            _postUrl = value
        End Set
    End Property

    ''' <summary>
    ''' This is the reponse back from the http post back to PayPal.
    ''' Possible values are "VERIFIED" or "INVALID"
    ''' </summary>
    Private Property Response() As String
        Get
            Return _response
        End Get
        Set(value As String)
            _response = value
        End Set
    End Property

    Private Property RequestLength() As String
        Get
            Return _strRequest
        End Get
        Set(value As String)
            _strRequest = value
        End Set
    End Property

    ''' <summary>
    ''' Provide your outgoing email server to use are your SMTP host
    ''' </summary>
    Public Property SmtpHost() As String
        Get
            Return _smtpHost
        End Get
        Set(value As String)
            _smtpHost = value
        End Set
    End Property

    ''' <summary>
    ''' Provide the port your outgoing SMTP host uses
    ''' </summary>
    Public Property SmtpPort() As String
        Get
            Return _smtpPort
        End Get
        Set(value As String)
            _smtpPort = value
        End Set
    End Property

    ''' <summary>
    ''' This is the email address that will show to the customer and you. This most likely
    ''' needs to be a valid email address that your SMTP server will accept
    ''' Examples would be something like no-reply@yourdomain.com
    ''' </summary>
    Public Property FromEmail() As String
        Get
            Return _fromEmail
        End Get
        Set(value As String)
            _fromEmail = value
        End Set
    End Property

    ''' <summary>
    ''' This is the password that the FromEmail property will use. This needs to be the password
    ''' for the email account itself
    ''' </summary>
    Public Property FromEmailPassword() As String
        Get
            Return _fromEmailPassword
        End Get
        Set(value As String)
            _fromEmailPassword = value
        End Set
    End Property

    ''' <summary>
    ''' This is the email address that you use for yourself. This should be set to
    ''' the email that is registered for your PayPal account.
    ''' </summary>
    Public Property ToEmail() As String
        Get
            Return _toEmail
        End Get
        Set(value As String)
            _toEmail = value
        End Set
    End Property

    ''' <summary>
    ''' Email address or Account ID of the payment recipient.  This is equivalent
    '''  to the value of receiver_email if the payment is sent to the primary account
    ''' , which is most cases it is.  This value is that value of what is set in the button html
    ''' markup.  This value also get normalized to lowercase when coming back from PayPal
    ''' </summary>
    Private Property Business() As String
        Get
            Return _business
        End Get
        Set(value As String)
            _business = value
        End Set
    End Property


    ''' <summary>
    ''' Unique transaction ID generated by PayPal. Helpful to use for checking
    '''  against fraud to make sure the transaction hasn't already occured.
    ''' </summary>
    Private Property TXN_ID() As String
        Get
            Return _txnID
        End Get
        Set(value As String)
            _txnID = value
        End Set
    End Property

    ''' <summary>
    ''' Type of transaction from the customer. Possible values are
    ''' "cart", "express_checkout", "send_money", "virtual_terminal", "web-accept"
    ''' </summary>
    Private Property TXN_Type() As String
        Get
            Return _txnType
        End Get
        Set(value As String)
            _txnType = value
        End Set
    End Property

    ''' <summary>
    ''' This is the status of the payment from the Customer.Possible values are: 
    ''' "Canceled_Reversal", "Completed", "Denied", "Expired", "Failed", "Pending",
    '''  "Processed", "Refunded", "Reversed", "Voided"
    ''' </summary>
    Private Property PaymentStatus() As String
        Get
            Return _paymentStatus
        End Get
        Set(value As String)
            _paymentStatus = value
        End Set
    End Property

    ''' <summary>
    ''' Primary email address of you, the recipient, of the payment.
    ''' </summary>
    Private Property ReceiverEmail() As String
        Get
            Return _receiverEmail
        End Get
        Set(value As String)
            _receiverEmail = value
        End Set
    End Property

    ''' <summary>
    ''' unique account ID of the payment recipient, which is most likely yourself.
    ''' </summary>
    Private Property ReceiverID() As String
        Get
            Return _receiverID
        End Get
        Set(value As String)
            _receiverID = value
        End Set
    End Property

    ''' <summary>
    ''' This is the item name passed by yourself or if the customer if you let them enter in an item name
    ''' </summary>
    Private Property ItemName() As String
        Get
            Return _itemName
        End Get
        Set(value As String)
            _itemName = value
        End Set
    End Property

    ''' <summary>
    ''' This is the item number you set for your own tracking purposes. It is not required by PayPal
    ''' so if you didn't set it most likely will come back blank.
    ''' </summary>
    Private Property ItemNumber() As String
        Get
            Return _itemNumber
        End Get
        Set(value As String)
            _itemNumber = value
        End Set
    End Property

    ''' <summary>
    ''' Quantity of the item ordered by the customer
    ''' </summary>
    Private Property Quantity() As String
        Get
            Return _quantity
        End Get
        Set(value As String)
            _quantity = value
        End Set
    End Property

    ''' <summary>
    ''' Quantity of the items in the shopping cart from the Customer
    ''' </summary>
    Private Property QuantityCartItems() As String
        Get
            Return _qtyCartItems
        End Get
        Set(value As String)
            _qtyCartItems = value
        End Set
    End Property

    ''' <summary>
    ''' Invoice number passed by yourself, if you didn't pass it to PayPal then this is omitted.
    ''' </summary>
    Private Property Invoice() As String
        Get
            Return _invoice
        End Get
        Set(value As String)
            _invoice = value
        End Set
    End Property

    ''' <summary>
    ''' Custom value passed by yourself with the item.
    ''' </summary>
    Private Property [Custom]() As String
        Get
            Return _custom
        End Get
        Set(value As String)
            _custom = value
        End Set
    End Property

    ''' <summary>
    ''' Memo entered in by the customer on PayPal website note field
    ''' </summary>
    Private Property Memo() As String
        Get
            Return _memo
        End Get
        Set(value As String)
            _memo = value
        End Set
    End Property

    ''' <summary>
    ''' Amount of tax charged on the payment
    ''' </summary>
    Private Property Tax() As String
        Get
            Return _tax
        End Get
        Set(value As String)
            _tax = value
        End Set
    End Property

    ''' <summary>
    ''' Full USD amount of customer's payment before the PayPal fee is subtracted
    ''' </summary>
    Private Property PaymentGross() As String
        Get
            Return _paymentGross
        End Get
        Set(value As String)
            _paymentGross = value
        End Set
    End Property

    ''' <summary>
    ''' Date Time stamp created by PayPal in the following format: 
    ''' HH:MM:SS DD Mmm YY, YYYY PST
    ''' </summary>
    Private Property PaymentDate() As String
        Get
            Return _paymentDate
        End Get
        Set(value As String)
            _paymentDate = value
        End Set
    End Property

    ''' <summary>
    ''' PayPal's transaction fees associated with purchase.
    ''' </summary>
    Private Property PaymentFee() As String
        Get
            Return _paymentFee
        End Get
        Set(value As String)
            _paymentFee = value
        End Set
    End Property


    ''' <summary>
    ''' This is the email that the customer used on PayPal or that
    ''' is registered with PayPal
    ''' </summary>
    Private Property PayerEmail() As String
        Get
            Return _payerEmail
        End Get
        Set(value As String)
            _payerEmail = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's phone number
    ''' </summary>
    Private Property PayerPhone() As String
        Get
            Return _payerPhone
        End Get
        Set(value As String)
            _payerPhone = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's company name if they represent a business
    ''' </summary>
    Private Property PayerBusinessName() As String
        Get
            Return _payerBusinessName
        End Get
        Set(value As String)
            _payerBusinessName = value
        End Set
    End Property

    ''' <summary>
    ''' This variable is only set if the payment_status=Pending. Possible values are the following:
    ''' "address", "authorization", "echeck", "intl", "multi-currency", "unilateral", "upgrade",
    '''  "verify", other"
    ''' </summary>
    Private Property PendingReason() As String
        Get
            Return _pendingReason
        End Get
        Set(value As String)
            _pendingReason = value
        End Set
    End Property

    ''' <summary>
    ''' This is indicated from what is set in your PayPal profile settings
    ''' </summary>
    Private Property ShippingMethod() As String
        Get
            Return _shippingMethod
        End Get
        Set(value As String)
            _shippingMethod = value
        End Set
    End Property

    ''' <summary>
    ''' Shipping charges associated with the order.
    ''' </summary>
    Private Property Shipping() As String
        Get
            Return _shipping
        End Get
        Set(value As String)
            _shipping = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's First Name
    ''' </summary>
    Private Property PayerFirstName() As String
        Get
            Return _firstName
        End Get
        Set(value As String)
            _firstName = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's Last Name
    ''' </summary>
    Private Property PayerLastName() As String
        Get
            Return _lastName
        End Get
        Set(value As String)
            _lastName = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's street address
    ''' </summary>
    Private Property PayerAddress() As String
        Get
            Return _address
        End Get
        Set(value As String)
            _address = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's city
    ''' </summary>
    Private Property PayerCity() As String
        Get
            Return _city
        End Get
        Set(value As String)
            _city = value
        End Set
    End Property

    ''' <summary>
    ''' Customer state of address
    ''' </summary>
    Private Property PayerState() As String
        Get
            Return _state
        End Get
        Set(value As String)
            _state = value
        End Set
    End Property

    ''' <summary>
    ''' Zip code of customer's address
    ''' </summary>
    Private Property PayerZipCode() As String
        Get
            Return _zip
        End Get
        Set(value As String)
            _zip = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's country
    ''' </summary>
    Private Property PayerCountry() As String
        Get
            Return _country
        End Get
        Set(value As String)
            _country = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's 2 character country code
    ''' </summary>
    Private Property PayerCountryCode() As String
        Get
            Return _countryCode
        End Get
        Set(value As String)
            _countryCode = value
        End Set
    End Property

    ''' <summary>
    ''' The the address provided is either confirmed or uncomfirmed from PayaPal. Possible values  from PayPal
    ''' are going to be "confirmed" or "unconfirmed"
    ''' </summary>
    Private Property PayerAddressStatus() As String
        Get
            Return _addressStatus
        End Get
        Set(value As String)
            _addressStatus = value
        End Set
    End Property

    ''' <summary>
    ''' Customer either had a verified or unverified account with PayPal. 
    ''' Possible return values from PayPal are "verified" or "unverified"
    ''' </summary>
    Private Property PayerStatus() As String
        Get
            Return _payerStatus
        End Get
        Set(value As String)
            _payerStatus = value
        End Set
    End Property

    ''' <summary>
    ''' Customer's unique ID
    ''' </summary>
    Private Property PayerID() As String
        Get
            Return _payerID
        End Get
        Set(value As String)
            _payerID = value
        End Set
    End Property

    ''' <summary>
    ''' Type of payment from Customer. Possible values from PayPal are "echeck" and "instant"
    ''' </summary>
    Private Property PaymentType() As String
        Get
            Return _paymentType
        End Get
        Set(value As String)
            _paymentType = value
        End Set
    End Property

    ''' <summary>
    ''' This is the version number of the IPN that makes the post.
    ''' </summary>
    Private Property NotifyVersion() As String
        Get
            Return _notifyVersion
        End Get
        Set(value As String)
            _notifyVersion = value
        End Set
    End Property

    ''' <summary>
    ''' An encrypted string that is used to validate the transaction. You don't have to use this for anything
    '''  unless you want to keep it and store it for your records.
    ''' </summary>
    Private Property VerifySign() As String
        Get
            Return _verifySign
        End Get
        Set(value As String)
            _verifySign = value
        End Set
    End Property


    ''' <summary>
    ''' Full USD amount of customer's payment before the PayPal fee is subtracted
    ''' </summary>
    Private Property Currency() As String
        Get
            Return _currency
        End Get
        Set(value As String)
            _currency = value
        End Set
    End Property
#End Region


#Region "Fill Properties"

    Private Sub fillProperties()
        Me.RequestLength = HttpContext.Current.Request.Form.ToString()
        Me.PayerCity = HttpContext.Current.Request.Form("address_city")
        Me.PayerCountry = HttpContext.Current.Request.Form("address_country")
        Me.PayerCountryCode = HttpContext.Current.Request.Form("address_country_code")
        Me.PayerState = HttpContext.Current.Request.Form("address_state")
        Me.PayerAddressStatus = HttpContext.Current.Request.Form("address_status")
        Me.PayerAddress = HttpContext.Current.Request.Form("address_street")
        Me.PayerZipCode = HttpContext.Current.Request.Form("address_zip")
        Me.PayerFirstName = HttpContext.Current.Request.Form("first_name")
        Me.PayerLastName = HttpContext.Current.Request.Form("last_name")
        Me.PayerBusinessName = HttpContext.Current.Request.Form("payer_business_name")
        Me.PayerEmail = HttpContext.Current.Request.Form("payer_email")
        Me.PayerID = HttpContext.Current.Request.Form("payer_id")
        Me.PayerStatus = HttpContext.Current.Request.Form("payer_status")
        Me.PayerPhone = HttpContext.Current.Request.Form("contact_phone")
        Me.Business = HttpContext.Current.Request.Form("business")
        Me.ItemName = HttpContext.Current.Request.Form("item_name")
        Me.ItemNumber = HttpContext.Current.Request.Form("item_number")
        Me.Quantity = HttpContext.Current.Request.Form("quantity")
        Me.ReceiverEmail = HttpContext.Current.Request.Form("receiver_email")
        Me.ReceiverID = HttpContext.Current.Request.Form("receiver_id")
        Me.[Custom] = HttpContext.Current.Request.Form("custom")
        Me.Memo = HttpContext.Current.Request.Form("memo")
        Me.Invoice = HttpContext.Current.Request.Form("invoice")
        Me.Tax = HttpContext.Current.Request.Form("tax")
        Me.QuantityCartItems = HttpContext.Current.Request.Form("num_cart_items")
        Me.PaymentDate = HttpContext.Current.Request.Form("payment_date")
        Me.PaymentStatus = HttpContext.Current.Request.Form("payment_status")
        Me.PaymentType = HttpContext.Current.Request.Form("payment_type")
        Me.PendingReason = HttpContext.Current.Request.Form("pending_reason")
        Me.TXN_ID = HttpContext.Current.Request.Form("txn_id")
        Me.TXN_Type = HttpContext.Current.Request.Form("txn_type")
        Me.Currency = HttpContext.Current.Request.Form("mc_currency")
        Me.PaymentFee = HttpContext.Current.Request.Form("mc_fee")
        Me.PaymentGross = HttpContext.Current.Request.Form("mc_gross")
        Me.NotifyVersion = HttpContext.Current.Request.Form("notify_version")
        Me.VerifySign = HttpContext.Current.Request.Form("verify_sign")
    End Sub

#End Region

    'public double GrossTotal { get; set; }
    'public int InvoiceNumber { get; set; }
    'public string PaymentStatus { get; set; }
    'public string PayerFirstName { get; set; }
    'public double PaymentFee { get; set; }
    'public string BusinessEmail { get; set; }
    'public string PayerEmail { get; set; }
    'public string TxToken { get; set; }
    'public string PayerLastName { get; set; }
    'public string ReceiverEmail { get; set; }
    'public string ItemName { get; set; }
    'public string Currency { get; set; }
    'public string TransactionId { get; set; }
    'public string SubscriberId { get; set; }
    'public string Custom { get; set; }





    Public Shared Function Parse(postData As String) As IPNHolder
        Dim sKey As [String], sValue As [String]
        Dim ph As New IPNHolder()

        'try
        '{
        '    //split response into string array using whitespace delimeter
        '    String[] StringArray = postData.Split('\n');

        '    // NOTE:
        '    /*
        '    * loop is set to start at 1 rather than 0 because first
        '    string in array will be single word SUCCESS or FAIL
        '    Only used to verify post data
        '    */

        '    // use split to split array we already have using "=" as delimiter
        '    int i;
        '    for (i = 1; i < StringArray.Length - 1; i++)
        '    {
        '        String[] StringArray1 = StringArray[i].Split('=');

        '        sKey = StringArray1[0];
        '        sValue = HttpUtility.UrlDecode(StringArray1[1]);

        '        // set string vars to hold variable names using a switch
        '        switch (sKey)
        '        {
        '            case "mc_gross":
        '                ph.GrossTotal = Convert.ToDouble(sValue);
        '                break;

        '            case "invoice":
        '                ph.InvoiceNumber = Convert.ToInt32(sValue);
        '                break;

        '            case "payment_status":
        '                ph.PaymentStatus = Convert.ToString(sValue);
        '                break;

        '            case "first_name":
        '                ph.PayerFirstName = Convert.ToString(sValue);
        '                break;

        '            case "mc_fee":
        '                ph.PaymentFee = Convert.ToDouble(sValue);
        '                break;

        '            case "business":
        '                ph.BusinessEmail = Convert.ToString(sValue);
        '                break;

        '            case "payer_email":
        '                ph.PayerEmail = Convert.ToString(sValue);
        '                break;

        '            case "Tx Token":
        '                ph.TxToken = Convert.ToString(sValue);
        '                break;

        '            case "last_name":
        '                ph.PayerLastName = Convert.ToString(sValue);
        '                break;

        '            case "receiver_email":
        '                ph.ReceiverEmail = Convert.ToString(sValue);
        '                break;

        '            case "item_name":
        '                ph.ItemName = Convert.ToString(sValue);
        '                break;

        '            case "mc_currency":
        '                ph.Currency = Convert.ToString(sValue);
        '                break;

        '            case "txn_id":
        '                ph.TransactionId = Convert.ToString(sValue);
        '                break;

        '            case "custom":
        '                ph.Custom = Convert.ToString(sValue);
        '                break;

        '            case "subscr_id":
        '                ph.SubscriberId = Convert.ToString(sValue);
        '                break;
        '        }
        '    }

        '    return ph;
        '}
        'catch (Exception ex)
        '{
        '    throw ex;
        '}

        'ph.PayerCity = "";
        'ph.PayerCountry = "";
        'ph.PayerCountryCode = "";
        'ph.PayerState = "";
        'ph.PayerAddressStatus = "";
        'ph.PayerAddress = "";
        'ph.PayerZipCode = "";
        'ph.PayerFirstName = "";
        'ph.PayerLastName = "";
        'ph.PayerBusinessName = "";
        'ph.PayerEmail = "";
        'ph.PayerID = "";
        'ph.PayerStatus = "";
        'ph.PayerPhone = "";
        'ph.Business = "";
        'ph.ItemName = "";
        'ph.ItemNumber = "";
        'ph.Quantity = "";
        'ph.ReceiverEmail = "";
        'ph.ReceiverID = "";
        'ph.Custom = "";
        'ph.Memo = "";
        'ph.Invoice = "";
        'ph.Tax = "";
        'ph.QuantityCartItems = "";
        'ph.PaymentDate = "";
        'ph.PaymentStatus = "";
        'ph.PaymentType = "";
        'ph.PendingReason = "";
        'ph.TXN_ID = "";
        'ph.TXN_Type = "";
        'ph.PaymentFee = "";
        'ph.PaymentGross = "";
        'ph.NotifyVersion = "";
        'ph.VerifySign = "";



        ph.RequestLength = HttpContext.Current.Request.Params.ToString()

        ph.PayerCity = HttpContext.Current.Request.Params("address_city")
        ph.PayerCountry = HttpContext.Current.Request.Params("address_country")
        ph.PayerCountryCode = HttpContext.Current.Request.Params("address_country_code")
        ph.PayerState = HttpContext.Current.Request.Params("address_state")
        ph.PayerAddressStatus = HttpContext.Current.Request.Params("address_status")
        ph.PayerAddress = HttpContext.Current.Request.Params("address_street")
        ph.PayerZipCode = HttpContext.Current.Request.Params("address_zip")
        ph.PayerFirstName = HttpContext.Current.Request.Params("first_name")
        ph.PayerLastName = HttpContext.Current.Request.Params("last_name")
        ph.PayerBusinessName = HttpContext.Current.Request.Params("payer_business_name")
        ph.PayerEmail = HttpContext.Current.Request.Params("payer_email")
        ph.PayerID = HttpContext.Current.Request.Params("payer_id")
        ph.PayerStatus = HttpContext.Current.Request.Params("payer_status")
        ph.PayerPhone = HttpContext.Current.Request.Params("contact_phone")
        ph.Business = HttpContext.Current.Request.Params("business")
        ph.ItemName = HttpContext.Current.Request.Params("item_name")
        ph.ItemNumber = HttpContext.Current.Request.Params("item_number")
        ph.Quantity = HttpContext.Current.Request.Params("quantity")
        ph.ReceiverEmail = HttpContext.Current.Request.Params("receiver_email")
        ph.ReceiverID = HttpContext.Current.Request.Params("receiver_id")
        ph.[Custom] = HttpContext.Current.Request.Params("custom")
        ph.Memo = HttpContext.Current.Request.Params("memo")
        ph.Invoice = HttpContext.Current.Request.Params("invoice")
        ph.Tax = HttpContext.Current.Request.Params("tax")
        ph.QuantityCartItems = HttpContext.Current.Request.Params("num_cart_items")
        ph.PaymentDate = HttpContext.Current.Request.Params("payment_date")
        ph.PaymentStatus = HttpContext.Current.Request.Params("payment_status")
        ph.PaymentType = HttpContext.Current.Request.Params("payment_type")
        ph.PendingReason = HttpContext.Current.Request.Params("pending_reason")
        ph.TXN_ID = HttpContext.Current.Request.Params("txn_id")
        ph.TXN_Type = HttpContext.Current.Request.Params("txn_type")
        ph.PaymentFee = HttpContext.Current.Request.Params("mc_fee")
        ph.PaymentGross = HttpContext.Current.Request.Params("mc_gross")
        ph.NotifyVersion = HttpContext.Current.Request.Params("notify_version")
        ph.VerifySign = HttpContext.Current.Request.Params("verify_sign")
        ph.Currency = HttpContext.Current.Request.Params("mc_currency")

        If ph.Business Is Nothing Then
            ph.Business = ""
        End If





        Return ph
    End Function


    ''' <summary>
    ''' This makes the post back to PayPal to verify the order.
    ''' </summary>
    'public void MakeHttpPost()
    '{
    '    HttpWebRequest req = (HttpWebRequest)WebRequest.Create(this.PostUrl);

    '    req.Method = "POST";
    '    req.ContentLength = this.RequestLength.Length + 21; 
    '    req.ContentType = "application/x-www-form-urlencoded";
    '    byte[] param = HttpContext.Current.Request.BinaryRead(HttpContext.Current.Request.ContentLength);
    '    this.RequestLength = Encoding.ASCII.GetString(param);
    '    this.RequestLength += "&cmd=_notify-validate";
    '    req.ContentLength = this.RequestLength.Length;

    '    StreamWriter streamOut = new StreamWriter(req.GetRequestStream(), System.Text.Encoding.ASCII);
    '    streamOut.Write(this.RequestLength);
    '    streamOut.Close();
    '    StreamReader streamIn = new StreamReader(req.GetResponse().GetResponseStream());
    '    this.Response = streamIn.ReadToEnd();
    '    streamIn.Close();

    '}

    '#endregion
End Class


